SUCCESSFULL_STATUS_CODE = 200
CREATED_STATUS_CODE = 201
BAD_REQUEST_STATUS_CODE = 400
CONFLICT_STATUS_CODE = 409
NOT_FOUND_STATUS_CODE = 404
DELETED_SUCCESFULL_STATUS_CODE = 204
UNAUTHORIZED_STATUS_CODE = 401
INTERNAL_SERVER_STATUS_CODE = 500